#!/bin/bash
###############################################################################################
# Türkçe
# =======
# Betik, veri kaybı olmadan her zaman en son sürümü günceller.
# Olası güvenlik açığı nedeniyle hizmet “vaultwarden” kullanıcısı ile çalıştırılıyor
# Ortam değişkenlerini içeren dosya /opt/vaultwarden/environment konumunda bulunur.
# Betik, henüz ön uçta Nginx gibi bir web hizmetini kurup yapılandırmaz.
# Debian 12'de test ettim.
#
# Kemal Oktay Aktoğan (oktay454) tarafından yazılmıştır.
# İletişim: iletisim@oktayaktogan.com.tr
###############################################################################################
# English
# =======
#
# The script, make always update latest version without data loss.
# Due to possible security vulnerability, the service is being run with the user “vaultwarden”
# The file containing the environment variables is located at /opt/vaultwarden/environment.
# The script, it does not yet install and configure a web service like Nginx on the front end.
# I tested on Debian 12.
#
# Writed by Kemal Oktay Aktoğan (aka oktay454)
# Contact: iletisim@oktayaktogan.com.tr
###############################################################################################

set -e

TEMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TEMP_DIR}"' EXIT

USER_NAME="vaultwarden"
GROUP_NAME="${USER_NAME}"
BASE_DIR="/opt/${USER_NAME}"
SERVICE_FILE="/etc/systemd/system/vaultwarden.service"
ENVIRONMENT_FILE="${BASE_DIR}/environment"

useradd -d "${BASE_DIR}" -m -r -U "${USER_NAME}" -s /usr/sbin/nologin || true

wget https://raw.githubusercontent.com/jjlin/docker-image-extract/main/docker-image-extract -O "${TEMP_DIR}/docker-image-extract" 
chmod +x "${TEMP_DIR}/docker-image-extract"
"${TEMP_DIR}/docker-image-extract" -o "${TEMP_DIR}" vaultwarden/server:alpine

install -d -o "${USER_NAME}" -g "${GROUP_NAME}" "${BASE_DIR}"
test -f "${ENVIRONMENT_FILE}" || touch "${ENVIRONMENT_FILE}"
rm -rf "${BASE_DIR}/web-vault/"
cp -rf "${TEMP_DIR}/web-vault/" "${BASE_DIR}"
rm -f "${BASE_DIR}/vaultwarden"
install -Dm0755 "${TEMP_DIR}/vaultwarden" "${BASE_DIR}/vaultwarden"
install -d -o "${USER_NAME}" -g "${GROUP_NAME}" "${BASE_DIR}/data"
chown -R ${USER_NAME}:${GROUP_NAME} "${BASE_DIR}"

cat > "${SERVICE_FILE}" << SERVICE
[Unit]
Description=Vaultwarden
After=network-online.target
Wants=network-online.target

[Service]
EnvironmentFile=${ENVIRONMENT_FILE}
User=${USER_NAME}
Group=${GROUP_NAME}
WorkingDirectory=${BASE_DIR}
ExecStart=${BASE_DIR}/vaultwarden
Restart=always

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable vaultwarden.service
systemctl restart vaultwarden.service
